"""Build one Airflow DAG per TableConfig.

This is where dependency injection happens: the engine class is looked up by
name in ENGINE_REGISTRY and instantiated lazily inside the operator callables
(per spec §6.11.5 — Spark cold-start is 30-45s so we share the cached
SparkSession across tasks in the same worker).

No TODOs live here. Participants do not edit this file.
"""
from __future__ import annotations

import logging
import os
from datetime import date, datetime

from airflow import DAG
from airflow.operators.python import PythonOperator

from internal_etl_package.alerting import slack_callback_on_failure
from internal_etl_package.config_loader import TableConfig
from internal_etl_package.engines.base import TableEngine
from internal_etl_package.engines.spark_engine import SparkIcebergEngine
from internal_etl_package.engines.trino_engine import TrinoIcebergEngine
from internal_etl_package.ledger import Ledger
from internal_etl_package.merger import merge_table
from internal_etl_package.quality import (
    completeness,
    consistency,
    freshness,
    post_audit,
    volume,
)


log = logging.getLogger(__name__)


ENGINE_REGISTRY: dict[str, type[TableEngine]] = {
    "spark": SparkIcebergEngine,
    "trino": TrinoIcebergEngine,
}


def _ledger_dsn() -> str:
    user = os.environ.get("POSTGRES_USER", "airflow")
    password = os.environ.get("POSTGRES_PASSWORD", "airflow")
    db = os.environ.get("POSTGRES_DB", "airflow")
    host = os.environ.get("POSTGRES_HOST", "postgres")
    return f"postgresql://{user}:{password}@{host}/{db}"


def _build_engine(table_config: TableConfig) -> TableEngine:
    engine_cls = ENGINE_REGISTRY[table_config.engine]
    return engine_cls()


def _pre_audit_callable(table_config: TableConfig):
    def _pre_audit(**_context):
        engine = _build_engine(table_config)
        for check in (freshness, volume, completeness, consistency):
            try:
                result = check(table_config, engine)
                log.info(
                    f"pre_audit/{check.__name__}: {result.status} — {result.message}"
                )
            except Exception as e:  # noqa: BLE001
                # First-run safety: the target table doesn't exist before the
                # initial merge. pre_audit reports state, it should not fail
                # the DAG. post_audit is the strict gate.
                log.warning(f"pre_audit/{check.__name__} skipped: {e}")
    return _pre_audit


def _merge_callable(table_config: TableConfig):
    def _merge(**context):
        engine = _build_engine(table_config)
        ledger = Ledger(_ledger_dsn())
        execution_date = _execution_date_from_context(context)
        merge_table(table_config, execution_date, engine, ledger)
    return _merge


def _post_audit_callable(table_config: TableConfig):
    def _post_audit(**_context):
        engine = _build_engine(table_config)
        post_audit(table_config, engine)
    return _post_audit


def _execution_date_from_context(context: dict) -> date:
    """Pull the logical/execution date out of an Airflow task context.

    Different Airflow versions name this differently — accept whichever is
    present and fall back to today.
    """
    for key in ("logical_date", "execution_date", "data_interval_start"):
        value = context.get(key)
        if value is not None:
            return value.date() if hasattr(value, "date") else value
    ds = context.get("ds")
    if ds:
        return date.fromisoformat(ds)
    return date.today()


def build_dag(table_config: TableConfig) -> DAG:
    """Build the replicate__<schema>__<table> DAG for one config entry."""
    dag_id = f"replicate__{table_config.name.replace('.', '__')}"

    default_args = {
        "owner": "maria",
        "retries": 0,
        "on_failure_callback": slack_callback_on_failure,
    }

    with DAG(
        dag_id=dag_id,
        default_args=default_args,
        start_date=datetime(2024, 1, 1),
        schedule="@hourly",
        catchup=False,
        tags=["replication", table_config.engine, table_config.severity],
    ) as dag:
        pre = PythonOperator(
            task_id="pre_audit",
            python_callable=_pre_audit_callable(table_config),
        )
        merge = PythonOperator(
            task_id="merge",
            python_callable=_merge_callable(table_config),
        )
        post = PythonOperator(
            task_id="post_audit",
            python_callable=_post_audit_callable(table_config),
        )
        pre >> merge >> post

    return dag
